// =====================================================================
// To-do / Task REST API — Node.js + Express + MongoDB (Mongoose)
// ---------------------------------------------------------------------
// Tasks are now persisted in MongoDB instead of an in-memory array, so
// data survives server restarts. Single-file app with clear sections.
// =====================================================================

require("dotenv").config(); // load MONGODB_URI (and PORT) from .env
const express = require("express");
const mongoose = require("mongoose");

const app = express();
const PORT = process.env.PORT || 3000;
const MONGODB_URI = process.env.MONGODB_URI;

// Parse JSON request bodies (populates req.body for POST/PUT).
app.use(express.json());

// ---------------------------------------------------------------------
// Database connection
// ---------------------------------------------------------------------
if (!MONGODB_URI) {
  console.error("❌ Missing MONGODB_URI. Add it to your .env file.");
  process.exit(1);
}

mongoose
  .connect(MONGODB_URI)
  .then(() => console.log("✅ Connected to MongoDB"))
  .catch((err) => {
    console.error("❌ MongoDB connection error:", err.message);
    process.exit(1);
  });

// ---------------------------------------------------------------------
// Schema & Model
// ---------------------------------------------------------------------
// Mongoose schema enforces the data shape at the database layer.
const taskSchema = new mongoose.Schema(
  {
    title: { type: String, required: true, trim: true },
    completed: { type: Boolean, default: false },
  },
  {
    timestamps: true, // adds createdAt / updatedAt automatically
    // Reshape JSON output: expose `id` (string) instead of Mongo's `_id`,
    // and hide internal fields so responses match our clean API contract.
    toJSON: {
      virtuals: true,
      versionKey: false,
      transform: (doc, ret) => {
        ret.id = ret._id;
        delete ret._id;
      },
    },
  }
);

const Task = mongoose.model("Task", taskSchema);

// ---------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------

// Wrap async handlers so a rejected promise goes to the error middleware
// instead of crashing the process.
function wrap(handler) {
  return (req, res, next) => Promise.resolve(handler(req, res, next)).catch(next);
}

// Validate a title value: must be a non-empty (after trim) string.
function isValidTitle(value) {
  return typeof value === "string" && value.trim().length > 0;
}

// ---------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------

// GET / — root route. Confirms the server is up and lists the endpoints.
app.get(
  "/",
  wrap((req, res) => {
    res.json({
      message: "Task REST API (MongoDB) is running.",
      endpoints: {
        "GET /tasks": "List all tasks",
        "GET /tasks/:id": "Get a single task",
        "POST /tasks": "Create a task { title }",
        "PUT /tasks/:id": "Update a task { title?, completed? }",
        "DELETE /tasks/:id": "Delete a task",
      },
    });
  })
);

// GET /tasks — return every task, newest first (200).
app.get(
  "/tasks",
  wrap(async (req, res) => {
    const tasks = await Task.find().sort({ createdAt: -1 });
    res.status(200).json(tasks);
  })
);

// GET /tasks/:id — return one task by id, or 404 if not found / bad id.
app.get(
  "/tasks/:id",
  wrap(async (req, res) => {
    // An invalid ObjectId throws a CastError → handled below as 404.
    if (!mongoose.isValidObjectId(req.params.id)) {
      return res.status(404).json({ error: "Task not found" });
    }
    const task = await Task.findById(req.params.id);
    if (!task) {
      return res.status(404).json({ error: "Task not found" });
    }
    res.status(200).json(task);
  })
);

// POST /tasks — create a task from { title }. id is generated by MongoDB;
// completed defaults to false. Any client-supplied id/completed is ignored here.
app.post(
  "/tasks",
  wrap(async (req, res) => {
    const { title } = req.body || {};

    if (!isValidTitle(title)) {
      return res
        .status(400)
        .json({ error: "Title is required and must be a non-empty string" });
    }

    const task = await Task.create({ title: title.trim(), completed: false });
    res.status(201).json(task); // 201 Created
  })
);

// PUT /tasks/:id — update title and/or completed. Ignores any client `id`.
// 404 if the task doesn't exist; 400 if provided fields are invalid.
app.put(
  "/tasks/:id",
  wrap(async (req, res) => {
    const { title, completed } = req.body || {};

    // Validate only the fields that were actually provided.
    if (title !== undefined && !isValidTitle(title)) {
      return res
        .status(400)
        .json({ error: "Title, if provided, must be a non-empty string" });
    }
    if (completed !== undefined && typeof completed !== "boolean") {
      return res
        .status(400)
        .json({ error: "Completed, if provided, must be a boolean" });
    }

    if (!mongoose.isValidObjectId(req.params.id)) {
      return res.status(404).json({ error: "Task not found" });
    }

    // Build an update object from only the allowed, provided fields.
    const updates = {};
    if (title !== undefined) updates.title = title.trim();
    if (completed !== undefined) updates.completed = completed;

    const task = await Task.findByIdAndUpdate(req.params.id, updates, {
      returnDocument: "after", // return the UPDATED document
      runValidators: true, // enforce schema rules on update
    });

    if (!task) {
      return res.status(404).json({ error: "Task not found" });
    }
    res.status(200).json(task);
  })
);

// DELETE /tasks/:id — remove a task. 404 if not found, else 200 with confirmation.
app.delete(
  "/tasks/:id",
  wrap(async (req, res) => {
    if (!mongoose.isValidObjectId(req.params.id)) {
      return res.status(404).json({ error: "Task not found" });
    }
    const task = await Task.findByIdAndDelete(req.params.id);
    if (!task) {
      return res.status(404).json({ error: "Task not found" });
    }
    res.status(200).json({ message: "Task deleted", task });
  })
);

// ---------------------------------------------------------------------
// Error handling
// ---------------------------------------------------------------------

// Catch-all 404 for unknown routes → always respond with JSON.
app.use((req, res) => {
  res.status(404).json({ error: "Route not found" });
});

// Error-handling middleware MUST be last (4 args). Handles malformed JSON,
// Mongoose validation/cast errors, and any unexpected errors.
// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {
  if (err.type === "entity.parse.failed" || err instanceof SyntaxError) {
    return res.status(400).json({ error: "Invalid JSON in request body" });
  }
  if (err.name === "ValidationError") {
    return res.status(400).json({ error: err.message });
  }
  if (err.name === "CastError") {
    return res.status(404).json({ error: "Task not found" });
  }
  console.error(err);
  res.status(500).json({ error: "Internal server error" });
});

// ---------------------------------------------------------------------
// Start the server
// ---------------------------------------------------------------------
app.listen(PORT, () => {
  console.log(`Task API listening on http://localhost:${PORT}`);
});
